# This file was generated by GoReleaser. DO NOT EDIT.
class Fx < Formula
  desc "fx, a simple but powerful Function as a Service build tools"
  homepage "https://github.com/metrue/fx"
  url "https://github.com/metrue/fx/releases/download/0.3.2-alpha.295745b/fx_0.3.2-alpha.295745b_macOS_64-bit.tar.gz"
  version "0.3.2-alpha.295745b"
  sha256 "b2fa1d6081b5bd89f46eadc90cd2178f38328be479c498226d1ccdf7b17889d7"

  def install
    bin.install "fx"
  end
end
