# This file was generated by GoReleaser. DO NOT EDIT.
class Fx < Formula
  desc "fx, a simple but powerful Function as a Service build tools"
  homepage "https://github.com/metrue/fx"
  url "https://github.com/metrue/fx/releases/download/0.3.0-alpha.19a9682/fx_0.3.0-alpha.19a9682_macOS_64-bit.tar.gz"
  version "0.3.0-alpha.19a9682"
  sha256 "e8655d948fe8c960ec393cae0bfe53e0b2b2f5c350e4fa6805fa503a9e2c0186"

  def install
    bin.install "fx"
  end
end
