# This file was generated by GoReleaser. DO NOT EDIT.
class Px < Formula
  desc "px, a simple cli to manipulate process"
  homepage "https://github.com/metrue/px"

  def install
    bin.install "px"
  end
end
